class NodeCreateTask
  def initialize(node)
    @node = node
  end

  def create_xml
    xml = "<domain type='kvm' id='#{@node.id}'>"
    xml += "<name>#{@host.id}_#{@host.hostname}</name>"
    xml += "<uuid>#{@node.uuid}</uuid>"
    xml += "<description>This VM was generated by Nodion.</description>"
    xml += "<vcpu placement='static'>#{@node.plan.cpu_value}</vcpu>"
    xml += "<cpu mode='custom'>"
    xml += "<model fallback='allow'>vCPU</model>"
    xml += "<vendor>Nodion</vendor>"
    xml += "</cpu>"

    xml += "</domain>"
  end
end
